"""split post_log into fb/ig status columns

Revision ID: 79ea06351249
Revises: e1c1c6ebf70c
Create Date: 2026-05-11 14:50:08.020699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ea06351249'
down_revision = 'e1c1c6ebf70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fb_status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('fb_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ig_status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('ig_error', sa.Text(), nullable=True))
        batch_op.drop_column('error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.TEXT(), nullable=True))
        batch_op.drop_column('ig_error')
        batch_op.drop_column('ig_status')
        batch_op.drop_column('fb_error')
        batch_op.drop_column('fb_status')

    # ### end Alembic commands ###
