"""initial tables

Revision ID: e1bd2f069b06
Revises: 
Create Date: 2026-05-01 16:55:06.409409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bd2f069b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('bag_name', sa.String(length=256), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bag_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bag_queue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bag_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bag_queue_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('recent_pin_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.String(length=256), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin_id', 'tenant_id', name='uq_pin_tenant')
    )
    with op.batch_alter_table('recent_pin_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_pin_cache_used_at'), ['used_at'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'tenant_id', name='uq_setting_key_tenant')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('pending_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('bag_queue_id', sa.Integer(), nullable=False),
    sa.Column('reference_pin_id', sa.String(length=256), nullable=True),
    sa.Column('reference_url', sa.Text(), nullable=True),
    sa.Column('generated_image_url', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('discord_message_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_post_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bag_queue_id'], ['bag_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approvals_discord_message_id'), ['discord_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_approvals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('post_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('fb_post_id', sa.String(length=256), nullable=True),
    sa.Column('ig_post_id', sa.String(length=256), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['pending_approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_log_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_log_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_post_log_posted_at'))

    op.drop_table('post_log')
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pending_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_pending_approvals_discord_message_id'))
        batch_op.drop_index(batch_op.f('ix_pending_approvals_created_at'))

    op.drop_table('pending_approvals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('settings')
    with op.batch_alter_table('recent_pin_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_pin_cache_used_at'))

    op.drop_table('recent_pin_cache')
    with op.batch_alter_table('bag_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bag_queue_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_bag_queue_status'))
        batch_op.drop_index(batch_op.f('ix_bag_queue_created_at'))

    op.drop_table('bag_queue')
    # ### end Alembic commands ###
