"""add reference_url to bag_queue

Revision ID: e1c1c6ebf70c
Revises: e1bd2f069b06
Create Date: 2026-05-06 18:58:46.835824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c1c6ebf70c'
down_revision = 'e1bd2f069b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bag_queue', schema=None) as batch_op:
        batch_op.drop_column('reference_url')

    # ### end Alembic commands ###
