"""add fb_caption ig_caption to pending_approvals

Revision ID: f54ccc0c063d
Revises: 79ea06351249
Create Date: 2026-05-11 18:50:48.966703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54ccc0c063d'
down_revision = '79ea06351249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fb_caption', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ig_caption', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_approvals', schema=None) as batch_op:
        batch_op.drop_column('ig_caption')
        batch_op.drop_column('fb_caption')

    # ### end Alembic commands ###
